---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "master"
    schedule:
      interval: daily
    labels: ["topic: dependencies"]
    commit-message:
      prefix: "ci"
